use strict;
use warnings;
use Test::More;

# generated by Dist::Zilla::Plugin::Test::PodSpelling 2.002004
eval "use Test::Spelling 0.12; use Pod::Wordlist::hanekomu; 1" or die $@;


add_stopwords(<DATA>);
all_pod_files_spelling_ok('bin', 'lib');
__DATA__
subcommand
OpenSSH
littlechef
subshell
wildcard
DNS
subkeys
runlist
thawer
David
Golden
lib
Pantry
App
Model
Command
show
create
init
list
strip
sync
Node
edit
Role
Serializable
apply
Runlist
